mindmap
  root((OPENAI\n119 Models))
    chat(⚠️ chat\n1 models)
      Latest: chat-latest
    dall-e(⚠️ dall-e\n2 models)
      Latest: dall-e-2
    gpt-3.5(⚠️ gpt-3.5\n6 models)
      Latest: gpt-3.5-turbo-0125
    gpt-4(⚠️ gpt-4\n6 models)
      Latest: gpt-4.1-nano
    gpt-4o(⚠️ gpt-4o\n23 models)
      Latest: gpt-4o-search-preview-2025-03-11
    gpt-5(⚠️ gpt-5\n38 models)
      Latest: gpt-5-chat-latest
    gpt-audio(⚠️ gpt-audio\n6 models)
      Latest: gpt-audio-1.5
    gpt-image(⚠️ gpt-image\n5 models)
      Latest: gpt-image-2-2026-04-21
    gpt-realtime(⚠️ gpt-realtime\n9 models)
      Latest: gpt-realtime-whisper
    image(⚠️ image\n1 models)
      Latest: chatgpt-image-latest
    legacy(⚠️ legacy\n2 models)
      Latest: babbage-002
    moderation(⚠️ moderation\n2 models)
      Latest: omni-moderation-latest
    o-series(⚠️ o-series\n8 models)
      Latest: o4-mini
    text-embedding(⚠️ text-embedding\n3 models)
      Latest: text-embedding-3-large
    tts(⚠️ tts\n4 models)
      Latest: tts-1-hd-1106
    video(⚠️ video\n2 models)
      Latest: sora-2-pro
    whisper(⚠️ whisper\n1 models)
      Latest: whisper-1